sudo: false
language: node_js
node_js:
  - stable

cache: npm

script:
  - npm run build
  - tar -czvf dist.tar.gz dist/

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "dist.tar.gz"
  skip_cleanup: true